In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv("E:\\newing\\bank-additional-full.csv",sep=';')
data.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [11]:
cat_cols_df = data.select_dtypes(include=['object'])
cat_cols = list(cat_cols_df.columns)
print(cat_cols)

#code all categorical columns
for name in cat_cols:
    col = pd.Categorical(data[name])
    data[name] = col.codes
    

['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'y']


In [17]:
data_features = data.drop(['y'], axis = 1)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  int8   
 2   marital         41188 non-null  int8   
 3   education       41188 non-null  int8   
 4   default         41188 non-null  int8   
 5   housing         41188 non-null  int8   
 6   loan            41188 non-null  int8   
 7   contact         41188 non-null  int8   
 8   month           41188 non-null  int8   
 9   day_of_week     41188 non-null  int8   
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  int8   
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [13]:
data.corr()["y"]


age               0.030399
job               0.025122
marital           0.046203
education         0.057799
default          -0.099352
housing           0.011552
loan             -0.004909
contact          -0.144773
month            -0.006065
day_of_week       0.015967
duration          0.405274
campaign         -0.066357
pdays            -0.324914
previous          0.230181
poutcome          0.129789
emp.var.rate     -0.298334
cons.price.idx   -0.136211
cons.conf.idx     0.054878
euribor3m        -0.307771
nr.employed      -0.354678
y                 1.000000
Name: y, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, precision_recall_curve, classification_report, confusion_matrix, roc_curve, roc_auc_score


In [26]:
x_train, x_test, y_train, y_test = train_test_split(data_features,data['y'],test_size=0.3)

In [33]:
classifiers = {'RdFrst': RandomForestClassifier(n_estimators=100), 
               'LgRg': LogisticRegression(multi_class='ovr',solver = 'liblinear')}

n_classifiers = len(classifiers)

for index, (name, classifier) in enumerate(classifiers.items()):
    classifier.fit(x_train,np.ravel(y_train))

    y_predict = classifier.predict(x_test)
    accuracy = accuracy_score(y_test, y_predict)
    print(classification_report(y_test, y_predict))
    print(y_predict)
    print(accuracy_score(y_test, y_predict))
    print(confusion_matrix(y_test, y_predict))


              precision    recall  f1-score   support

           0       0.93      0.97      0.95     10911
           1       0.67      0.48      0.56      1446

    accuracy                           0.91     12357
   macro avg       0.80      0.72      0.75     12357
weighted avg       0.90      0.91      0.90     12357

[0 0 0 ... 0 0 0]
0.9112244072185806
[[10564   347]
 [  750   696]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95     10911
           1       0.70      0.37      0.49      1446

    accuracy                           0.91     12357
   macro avg       0.81      0.68      0.72     12357
weighted avg       0.90      0.91      0.90     12357

[0 0 0 ... 0 0 0]
0.9082301529497451
[[10681   230]
 [  904   542]]
